
customer:
  type: object
  additionalProperties: False
  properties: 
    name: 
      type: string
    description:
      type: string
    address:
      type: string
    city:
      type: string
    postal_code:
      type: string
    country:
      type: string
    website:
      type: string
    email:
      type: string
    phone:
      type: string
    contact_person:
      type: string
    vat_number:
      type: string

user:
  type: object
  additionalProperties: False
  properties: 
    name: 
      type: string
    surname:
      type: string
    username:
      type: string
    email:
      type: string
    phone:
      type: string
      blank: True
    mobile:
      type: string
      blank: True
    city:
      type: string
      blank: True
    group:
      type: string
      enum:
        - administrator
        - employee
        - project manager
    password: 
      type: string
      blank: True
    salt: 
      type: string
      blank: True
    salary:
      type: array
      items:
        additionalProperties: False
        properties:
          cost:
            type: number
          from:
            type: string
          to:
            type: string

project:
  type: object
  additionalProperties: False
  properties:
    customer:
      type: string
    type:
      type: string
    name: 
      type: string
    description:
      type: string
    contact_person:
      type: string
    start:
      type: string
    end:
      type: string
    tasks:
      type: array
      items:
        properties:
          name:
            type: string
    grand_total:
      type: number
      optional: True
    expences:
      type: number
      optional: True
    responsible:
      type: object
      additionalProperties: False
      properties:
        _id:
          type: string
        name:
          type: string
    employees:
      type: array
      items:
        optional: True
        additionalProperties: False
        properties:
          _id:
            type: string
          name:
            type: string

trip:
  type: object
  additionalProperties: False
  properties:
    user:
      type: string
    project:
      type: string
    description:
      type: string
    status: 
      type: string   
    start:
      type: string
    end:
      type: string
    country:
      type: string
    city:
      type: string
    accommodation:
      type: object
      additionalProperties: False
      properties:
        car:
           type: boolean
        hotel:
           type: boolean
        airplane:
           type: boolean

day:
  type: object
  additionalProperties: False
  properties:
    date:
      type: string
    users:
      optional: True
      type: array
      items:
        properties:
          user_id:
            type: string
          hours:
            optional: True
            type: array
            items: 
              properties:
                project:
                  type: string
                amount:
                  type: number
                isextra:
                  type: boolean
                note:
                  optional: True
                  type: string
                task:
                  type: integer
              
offer:
  type: object
  additionalProperties: False
  properties:
    project:
      type: string
    name:
      type: string
    description:
      type: string
    amount:
      type: number
    expences:
      type: boolean
    paydelay:
      type: integer
    customerref:
      type: string
    pdf:
      optional: True
      type: string

