
customer:
  type: object
  properties: 
    name: 
      type: string
    description:
      type: string
    address:
      type: string
    city:
      type: string
    postal_code:
      type: string
    country:
      type: string
    website:
      type: string
    email:
      type: string
    phone:
      type: string
    contact_person:
      type: string
    vat_number:
      type: string

user:
  type: object
  properties: 
    name: 
      type: string
    surname:
      type: string
    username:
      type: string
    email:
      type: string
    phone:
      type: string
    mobile:
      type: string
    city:
      type: string
    group:
      type: string
    password: 
      type: string
      blank: True
    salt: 
      type: string
      blank: True

project:
  type: object
  properties:
    customer:
      type: string
    type:
      type: string
    name: 
      type: string
    description:
      type: string
    contact_person:
      type: string
    start:
      type: string
    end:
      type: string
    grand_total:
      type: decimal
      optional: True
    expences:
      type: decimal
      optional: True
    responsible:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
    employees:
      type: array
      optional: True
      properties:
        _id:
          type: string
        name:
          type: string

